##reading in and cleaning data
library(pryr)
hpowerconsump <- read.csv("~/Documents/household_power_consumption.txt", header=FALSE, sep=";")
hpowerconsump$fulltime <- paste(hpowerconsump$V1,hpowerconsump$V2)
hpowerconsump$fulltime<-strptime(hpowerconsump$fulltime,format="%d/%m/%Y %H:%M:%S")
colnames(hpowerconsump) <- c("Date", "Time","Global_active_power","Global_Reactive_Power","Voltage","Global_Intensity", "Sub_Metering_1","Sub_Metering_2","Sub_Metering_3","Date_Time")
hpowerconsump<-hpowerconsump[-c(1), ]
objectsize<-object_size(hpowerconsump)
print(objectsize)
badsubsetpower<-hpowerconsump[hpowerconsump$Date_Time >= "2007-02-01" & hpowerconsump$Date_Time <"2007-02-03",]
subsetpower<-badsubsetpower[1:2880,]
subsetpower[,3] <- as.numeric(as.character(subsetpower[,3]))
subsetpower[,4] <- as.numeric(as.character(subsetpower[,4]))
subsetpower[,5] <- as.numeric(as.character(subsetpower[,5]))
subsetpower[,7] <- as.numeric(as.character(subsetpower[,7]))
subsetpower[,8] <- as.numeric(as.character(subsetpower[,8]))
subsetpower[,9] <- as.numeric(as.character(subsetpower[,9]))
## Making the plots
par(mfrow=c(2,2),mar=c(4,4,2,1), oma=c(0,0,2,0))
with(subsetpower, {plot(subsetpower$Date_Time,subsetpower$Global_active_power,type="l",yaxt='n',ylab="Global Active Power",xlab=" ",cex=.5)
                    axis(2, at = seq(0, 6, by = 2), las=2)
                    plot(Date_Time,Voltage,type="l",xlab="datetime",yaxt='n',cex=.5)
                    axis(2, at = seq(234, 246, by = 2), las=2,labels=c("234"," ","238"," ","242"," ","246"))
                    plot(Date_Time,Sub_Metering_1,type='n',xlab=" ",ylab="Energy sub metering",yaxt='n',cex=.5)
                    lines(subsetpower$Date_Time, subsetpower$Sub_Metering_1, type="l")
                    lines(subsetpower$Date_Time, subsetpower$Sub_Metering_2, type="l",col="red")
                    lines(subsetpower$Date_Time, subsetpower$Sub_Metering_3, type="l",col="blue")
                    legend("topright",lty=c(1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=.5,bty="n")
                    axis(2, at = seq(0, 30, by = 10), las=2)
                    plot(Date_Time,Global_Reactive_Power,type="l",ylab="Global_reactive_power",xlab="datetime",yaxt='n',cex=.5)
                    axis(2, at = seq(0.0, 0.5, by = 0.1), las=2)
                    })
dev.copy(png, file="plot4.png")
png("plot4.png", width = 480, height = 480)
dev.off()
